### ISSUE TITLE
Newer version uploaded to Berkshelf

### ISSUE THREAD

**Issue by bwvoss** [rapid7-cookbooks/nexpose#21]
Currently berkshelf only has up to 0.2.0 available for installation.  Is it possible to get all versions to the current version (0.2.2) updated and available for consumption via berkshelf?

**Comment by rhass-r7** [comment]
v0.2.2 has been released to supermarket. 

As a side note, sorry about the README.md being garbled in supermarket. I opened #22 for this issue.

**Comment by bwvoss** [comment]
Thanks Ryan!
