### ISSUE TITLE
Travis Builds are Failing for Windows

### ISSUE THREAD

**Issue by rhass** [rapid7-cookbooks/nexpose#29]
This is likely because the encrypted secrets were encrypted against my rhass-r7 account which no longer has access, and the keys were likely revoked. Unfortunately, you will need to recreate and re-encrypt the data to get this working again.

Let me know if you need any help fixing this, I am happy to do a Google Hangout or something to pair up with you. =) @asebastian-r7 @bcall-r7

**Comment by erran-r7** [comment]
@rhass ❤️ miss you man! I'll take a looksy.

**Comment by erran-r7** [comment]
@rhass yeah I think pairing with @asebastian-r7 or @bcall-r7 is probably the quickest way to go about it. 😅 I don't have context around what these encrypted values nor what is contained in `travis.enc`.

**Comment by rhass** [comment]
@asebastian-r7 @bcall-r7 -- Feel free to throw a calendar invite my way for when you have about 30 minutes or so.

@erran-r7 :heart_eyes: I miss you too! Say hello to the Belfast crew for me. =)

**Comment by rhass** [comment]
Stale issue. Closing.
