### ISSUE TITLE
Update URL/URI Attribute

### ISSUE THREAD

**Issue by jjscaria** [rapid7-cookbooks/nexpose#41]
Master has 
```default['nexpose']['installer']['uri'] = "http://download2.rapid7.com/download/NeXpose-v4/#{node['nexpose']['installer']['bin']}"```

These doesn't exist:
http://download2.rapid7.com/download/NeXpose-v4/Rapid7Setup-Linux64.bin
http://download2.rapid7.com/download/NeXpose-v4/Rapid7Setup-Windows64.exe

Should it be:
```default['nexpose']['installer']['uri'] = "http://download2.rapid7.com/download/InsightVM/#{node['nexpose']['installer']['bin']}"```

**Comment by bcall-r7** [comment]
PR here: https://github.com/rapid7-cookbooks/nexpose/pull/42

**Comment by bcall-r7** [comment]
This should now be fixed in master. Going to work on merging https://github.com/rapid7-cookbooks/nexpose/pull/36 The we will release a new version.

**Comment by jjscaria** [comment]
Thank you for the prompt response. Need to update ReadMe as well.
